server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location / {
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=300";
        try_files $uri =404;
    }

    gzip on;
    gzip_types application/javascript text/javascript;
}
